USE bdCatalogo;


INSERT INTO vino
VALUES('1', 'Aglianico fidelis 2018', 'Il vino aglianico fidelis che prende il nome di  celebra la sua maggiore fattura nella zona Doc del Aglianico collocata in Campania ed è considerato come uno dei vini DOCG. E  proprio qui che il  viene prodotto prevalentemente in quanto il suo principale vitigno il  Aglianico trova un ambiente molto adeguato per la sua crescita maturazione. I principali comuni dov è fatto il Aglianico Del Taburno Aglianico Del Taburno Docg sono:  Apollosa, Bonea, Castelpoto, Campoli Del Monte Taburno, Foglianese, Montesarchio, Paupisi, Torrecuso, Ponte, Benevento, Cautano, Vitulano, Tocco Claudio.Come suddetto esso fa parte della famiglia dei vini rossi i quali offrono essenzialmente peculiarità simili tra di loro e altre che invece rendono ogni vino rosso incomparabile nel suo genere. Sicuramente la prima tipicità da analizzare nei vini rossi è il colore che si differenzia a seconda "dell età" infatti sostanzialmente i vini rossi che offrono una colorazione rubino sono i più giovani, con l invecchiamento la colorazione diventa sempre più intensa e scura cambiando dal rosso vivo e brillante ad una sorta di bordeaux. Anche il sapore e l odore dei vini rossi variano a seconda dell età di quest ultimi, parlando del sapore dunque possiamo dire che i vini più giovani offrono un sapore più duro a differenza di contrariamente a rispetto a quelli invecchiati la ragione è che contengono più quantità di tannini i quali, con l invecchiamento del vino, si riducono lasciando spazio ad un sapore più morbido ed equilibrato. Riguardo l odore invece i vini invecchiati offrono note di legno (se affinati in botte) vaniglia, semi tostati e spezie, al contrario i vini giovani emanano aromi floreali e fruttati. La temperatura adatta per i vini rossi ancora una volta varia dall invecchiamento dello stesso ma in questo caso non si parla solo di vini giovani e vini vecchi ma anche di vini mediamente invecchiati. I vini mediamente invecchiati usufruiscono di una temperatura ideale di circa 12-13 °C in bottiglia e 14- 15 °C nel bicchiere, quelli molto invecchiati 15-17 °C in bottiglia e 18- 10 C° nel bicchiere. ', 
		11.50, 20.79, 'Campania', 'https://resizer.bernabei.it/ARTICOLI/L_926.png', 0, 'Rosso', 'Secco'),
      ('2', 'Chianti Montespertoli Docg', 'Il vino  che prende il nome di chianti montespertoli celebra la sua massima fattura nella zona Doc del Chianti collocata in Toscana ed ha indicazione come uno dei vini DOCG. E  proprio in tali zone che il  viene prodotto di più in quanto il suo principale vitigno il  Sangiovese trova un ambiente più consono per la sua crescita maturazione. I principali comuni dov è fatto il Chianti Chianti Montalbano Docg sono:  Capraia, Vinci, Carmignano, Lamporrecchio, Larciano, Quarrata, Serravalle. ',
		14, 12.75, 'Toscana', 'https://resizer.bernabei.it/ARTICOLI/L_3895.png', 0, 'Rosso', 'Secco'),
      ('3', 'Amarone Della Valpolicella Docg', 'Il vino rosso  prodotto per la maggior parte in Veneto è un vino ad indicazione DOCG. Stiamo parlando di un vino la cui produzione abbonda principalmente  nei comuni di  S.Ambrogio, Fumane, Negrar, S.Pietro Incariano (Valpolicella), dove il vitigno ha trovato le condizioni ottimali al totale sviluppo delle sue caratteristiche. L ottima qualità del vino rosso  tocca il punto più alto in taluni di comuni e specialmente nella zona doc di Valpolicella Stiamo parlando dicome la stragrande maggioranza dei vini rossi, di un vino molto più ricco rispetto ai vini bianchi, dai quali si distingue non solo per le differenti qualità organolettiche ma anche per i diversi modi di produzione ', 
		15.5, 19.90, 'Veneto', 'https://resizer.bernabei.it/ARTICOLI/L_7410.png', 0, 'Rosso', 'Secco'),
      ('4', 'Barolo Docg', 'Il vino  che prende il nome di  vanta la sua più grande produzione nella zona Doc del Barolo posta in Piemonte ed è considerato come uno dei vini DOCG. E  proprio qui che il  viene prodotto per la maggiore in quanto il suo principale vitigno il  Nebbiolo trova un ambiente maggiormente adeguato per la sua crescita maturazione. I principali comuni dov è fatto il Barolo Barolo Docg sono:  Barolo, Castiglione Falletto, Serralunga D alba, Cherasco, Diano D alba, Grinzane Cavour, La Morra, Monforte D alba, Novello, Roddi, Verduno. ', 
		13.5, 23.90, 'Piemonte', 'https://resizer.bernabei.it/ARTICOLI/L_4339.png', 0, 'Rosso', 'Secco'),
      ('5', 'Pinot Nero Doc', 'Il vino  che prende il nome di  decanta la sua più grande fattura nella zona Doc del Breganze situata in Veneto ed ha indicazione come uno dei vini DOC. E  proprio qui che il  viene prodotto maggiormente in quanto il suo principale vitigno il  Pinot Nero trova un ambiente maggiormente ideale per la sua crescita maturazione. I principali comuni dov è fatto il Breganze Pinot Nero Doc sono:  Breganze, Fara, Mason, E Marostica, Bassano, Sandrigo. ', 
		12.5, 8.60, 'Veneto', 'https://resizer.bernabei.it/ARTICOLI/L_2087.png', 0, 'Rosso', 'Secco'),
      ('6', 'Chardonnay delle venezie', 'Lo Chardonnay delle venezie rientra nella categoria dei vini bianchi ed è prodotto prevalentemente in Friuli Venezia Giulia dove il  Chardonnay ha trovato maggiormente un clima ideale per la sua maturazione. Il  viene fatto soprattutto nei comuni di  Tra Monfalcone E Trieste e nella zona DOC Carso, esso deriva non solo da  Chardonnay ma anche da   ed è considerato un tipo di vino DOC.Il  possiede peculiarità comuni agli altri vini di color bianco i quali in relazione alla tipologia possono passare da un colore giallo oro all ambrato ed in alcune varianti come in quelli dei vini giovani possono avere dei riflessi verdolini. Seguente specialità dei vini bianchi è la tipologia di odore che solitamente può presentare una prevalenza di aromi di fiori bianchi e gialli di erba appena tagliata e frutta fresca non ancora matura e quest ultima specialità  diventa sempre più pronunciata con l intensificazione della colorazione. ', 
		12, 3.80, 'Friuli Venezia Giulia', 'https://resizer.bernabei.it/ARTICOLI/L_391.png', 0, 'Bianco', 'Secco'),
      ('7', 'Pecorino 2020 I carbonari', 'Il Pecorino 2020 I carbonari fa parte dei vini bianchi ed è prodotto in maggioranza in Marche dove il  Pecorino ha trovato maggiormente un clima ideale per la sua maturazione. Il  vede la sua maggiore produzione nei comuni di  Offida, Ripatransone E Provincia Di Ascoli e nella zona DOC Offida, esso viene estratto non solo da  Pecorino ma anche da   ed è considerato un tipo di vino DOC.Il  offre peculiarità affini agli altri vini di color bianco i quali relativamente alla tipologia possono passare da un colore giallo oro all ambrato ed in certe tipologie come in quelli dei vini giovani possono presentare dei riflessi verdolini. Aggiuntiva peculiarità dei vini bianchi è la tipologia di odore che di norma può presentare una prevalenza di aromi di fiori bianchi e gialli di erba appena tagliata e frutta fresca non ancora matura e quest ultima peculiarità  diventa più forte con l aumento d intensità della colorazione', 
		13, 9.80, 'Marche', 'https://resizer.bernabei.it/ARTICOLI/L_9022.png', 0, 'Bianco', 'Secco'),
      ('8', 'Pinot Grigio Doc', 'Il Oltrepo Pavese Pinot Grigio Pinot Grigio Doc è parte della famiglia dei bianchi ed è prodotto principalmente in Lombardia dove il  Pinot Grigio ha trovato un clima ed una condizione ideali per la sua maturazione. Il  viene prodotto principalmente nei comuni di  Santa Maria Della Versa, Oliva, Gessi Montalto, Casteggio, Codevilla, Torrazza, Rivanazzano, Volpara, Casteggio, Retorbido, Montu , Montecalvo, Montu,  Roccade Giorgi, Cigognola, Canneto Pavese, Broni e nella zona DOC Oltrepo Pavese Pinot Grigio, esso viene fatto non solo tramite il  Pinot Grigio ma anche da   ed è considerato un tipo di vino DOC.Il  offre caratteristiche comuni agli altri vini di color bianco i quali a seconda della tipologia possono passare da un colore giallo oro all ambrato ed in certi tipi come in quelli dei vini giovani possono offrire dei riflessi verdolini. Seguente particolarità dei vini bianchi è il tipo di odore che sostanzialmente può presentare una maggioranza di aromi di fiori bianchi e gialli di erba appena tagliata e frutta fresca non ancora matura e quest ultima particolarità  diventa più forte con il rafforzamento della colorazione', 
		13, 6.50, 'Lombardia', 'https://resizer.bernabei.it/ARTICOLI/L_4178.png', 0, 'Bianco', 'Secco'),
      ('9', 'Trentino Traminer Aromatico Doc', 'Il Trentino Traminer Aromatico Doc è parte della famiglia dei bianchi ed è prodotto in maggioranza in Trentino dove il  Traminer Aromatico ha trovato un clima ed una condizione ideali per la sua maturazione. Il  vede la sua maggiore produzione nei comuni di  Rovere , Lavis, S.Michele, Mezzocorona, Trento, Rovereto, Isera, Mori e nella zona DOC Trentino, esso viene estratto non solo da  Traminer Aromatico ma anche da   ed è classificato un tipo di vino DOC.Il  offre singolarità comuni agli altri vini di color bianco i quali in relazione alla tipologia possono variare da un colore giallo oro all ambrato ed in certi tipi come in quelli dei vini giovani possono avere dei riflessi verdolini. Ulteriore tipicità dei vini bianchi è la tipologia di odore che generalmente può presentare una prevalenza di aromi di fiori bianchi e gialli di erba appena tagliata e frutta fresca non ancora matura e quest ultima tipicità  diventa più forte con l aumento d intensità della colorazione', 
		13.5, 10.80, 'Trentino', 'https://resizer.bernabei.it/ARTICOLI/L_6048.png', 0, 'Bianco', 'Secco'),
      ('10', 'Verdicchio Dei Castelli Di Jesi Bianco Doc', 'Il vino bianco  prodotto in maniera particolare in Marche è un vino , la cui coltivazione e preparazione abbonda in maniera particolare nei comuni di  Jesi, Staffolo, Cupramontana, S. Paolo, Poggio San Marcello, dove nel corso degli anni la tradizione del vino  si è trasformata in prodotto di lusso assoluto. Numerosi sono, infatti, i produttori di eccellenza collocati in questa regione, alcuni dei quali riescono a differenziare e ad emergere per per il sapore unico ed inconfondibile dei propri vini e per la qualità della loro coltivazione. Anche il vino Verdicchio Dei Castelli Di Jesi Bianco Doc presenta le caratteristiche generali di tutti i vini bianchi che, a differenza dei vini rossi, sono caratterizzati da una vinificazione che non prescrive il contatto tra vinacce e mosto in trasformazione. In relazione alla vinificazione dei vini bianchi, ovvero in merito a quell iter che consente all uva di tramutarsi in vino, si deve stare molto attenti visto che va evitato il contatto con l aria che potrebbe provocare ossidazione e dunque gustare il sapore del vino. Anche il vino Verdicchio Dei Castelli Di Jesi Bianco Doc si distingue per determinate caratteristiche che sono tipiche di  tutti i vini bianchi: il colore che ad un primo sguardo si presenta giallo in tonalità che variano dall ambrato al verdolino, dal dorato al paglierino, il profumo che per grandi linee assume i toni del floreale o del fruttato, il sapore in generale meno intenso rispetto a quello dei vini rossi. I vini bianchi,  di fatti, sono generalmente meno alcolici dei rossi e quindi più facilmente bevebili anche nei periodi caldi, e si differenziano per un sapore dai toni intensi ma delicati con lievi sfumature di liquirizia, cannella e tabacco biondo. ', 
		13, 9.90, 'Marche', 'https://resizer.bernabei.it/ARTICOLI/L_5665.png', 0, 'Bianco', 'Secco');